### ISSUE TITLE
Path Issue for Resources

### ISSUE THREAD

**Issue by gurumeditator** [atomicbits/scraml#109]
I m using .5.1 client generator and receiving the below error. I have verified the file exists. The same RAML file and resource locations will work in <.5.0 client generator:
```
 mvn io.atomicbits:scraml-maven-plugin:0.5.1:scraml@generate-client-sources -e -X
...
Unable to find resource /C:/Users/path/to/file/...
        at scala.sys.package$.error(package.scala:27)
        at io.atomicbits.scraml.ramlparser.parser.RamlToJsonParser$.parseToJson(RamltoJsonParser.scala:53)
        at io.atomicbits.scraml.ramlparser.parser.RamlToJsonParser$.parseToJson(RamltoJsonParser.scala:37)
        at io.atomicbits.scraml.ramlparser.parser.RamlParser.io$atomicbits$scraml$ramlparser$parser$RamlParser$$parseNested$1(RamlParser.scala:70)
        at io.atomicbits.scraml.ramlparser.parser.RamlParser$$anonfun$1.applyOrElse(RamlParser.scala:77)
        at io.atomicbits.scraml.ramlparser.parser.RamlParser$$anonfun$1.applyOrElse(RamlParser.scala:76)
        at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:141)
        at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:140)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at scala.collection.TraversableLike$class.collect(TraversableLike.scala:271)
        at scala.collection.AbstractTraversable.collect(Traversable.scala:104)
        at io.atomicbits.scraml.ramlparser.parser.RamlParser.io$atomicbits$scraml$ramlparser$parser$RamlParser$$parseNested$1(RamlParser.scala:76)
        at io.atomicbits.scraml.ramlparser.parser.RamlParser.parseRamlJsonDocument(RamlParser.scala:85)
        at io.atomicbits.scraml.ramlparser.parser.RamlParser.parse(RamlParser.scala:39)
        at io.atomicbits.scraml.generator.ScramlGenerator$.generateClassReps(ScramlGenerator.scala:109)
        at io.atomicbits.scraml.generator.ScramlGenerator$.generateFor(ScramlGenerator.scala:90)
        at io.atomicbits.scraml.generator.ScramlGenerator$.generateJavaCode(ScramlGenerator.scala:65)
        at io.atomicbits.scraml.generator.ScramlGenerator.generateJavaCode(ScramlGenerator.scala)
        at io.atomicbits.scraml.mvnplugin.ScramlMojo.execute(ScramlMojo.java:110)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
```

**Comment by rigolepe** [comment]
It's been reported and it is solved in 0.5.1b  I will release a proper 0.5.2 version soon, but 0.5.1b should get you going for now.
